notifications:
  email: false
dist: xenial
addons:
    ssh_known_hosts: adicu.com
language: python
python:
- '3.7'
script:
- python3 --version
before_install:
- openssl aes-256-cbc -K $encrypted_a6101146efef_key -iv $encrypted_a6101146efef_iv 
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa


deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after $TRAVIS_BUILD_DIR/dist/* travis@adicu.com:/srv/2020.devfe.st/public_html
    on: 
        branch: master
